name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3  # Atualizado para a versão mais recente do checkout
      - name: Set up Python 3.9
        uses: actions/setup-python@v4  # Atualizado para a versão mais recente do setup-python
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --prefer-install=basic  # Melhora a instalação do Poetry

      - name: Run tests
        run: |
          poetry run python manage.py test --noinput  # Impede a interação durante os testes
